[package]
name = "pinbot-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
twilight-http-ratelimiting = "0.11.0"
twilight-http = "0.11.0"
twilight-gateway = "0.11.0"
twilight-model = "0.11.0"
twilight-util = { default-features = false, features = ["builder"], version = "0.11.0" }
futures = "0.3.21"
serde = "1.0"
serde_json = "1.0"
url = "2.2.2"
lazy_static = "1.4"
log = "0.4"
simple_logger = "2.1"

[dependencies.tokio]
version = "1.0"
features = ["macros", "rt-multi-thread", "fs"]
default-features = false
