name: Publish Artifacts

on:
  push:
    branches: [ "master" ]
    paths-ignore: [ '*.md' ]

jobs:
  linux:
    name: Artifact Linux (x64)
    runs-on: ubuntu-latest
    container:
      image: ubuntu:16.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install Essentials
        run: |
          apt-get update
          apt-get upgrade -y
          apt-get install -y curl gcc
      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af #@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Build Artifact
        run: cargo build -r
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Linux x64
          path: target/release/pinbot-rs
  windows:
    name: Artifact Windows (x64)
    runs-on: windows-2019
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af #@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Build Artifact
        run: cargo build -r
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Windows x64
          path: target/release/pinbot-rs.exe
    name: Artifact macOS (Universal)
    runs-on: macos-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af #@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: x86_64-apple-darwin
      - name: Build Artifact (x64)
        run: cargo build -r --target=x86_64-apple-darwin
      - name: Build Artifact (M1)
        uses: actions/checkout@v4
          rustup target add aarch64-apple-darwin
        uses: dtolnay/rust-toolchain@stable
      - name: Combine Universal Darwin
          targets: x86_64-apple-darwin
        with:
          name: macOS universal
          path: pinbot-rs
